pastel:
  data-dir: "~/.pastel"
  host: "127.0.0.1"
  port: 9932
  user: "rt"
  pwd: "rt"

rest:
  host: "localhost"
  port: 4001

p2p:
  host: "127.0.0.1"
  port: 4444
  stun: False
  seeds:
    -
      host: "127.0.0.1"
      port: 4443
    -
      host: "127.0.0.1"
      port: 4442

